version: "3"

services:
  app:
    image: flamov/flamov-portfolio:latest
    container_name: app
    expose:
      - "3000"
    restart: unless-stopped
    env_file: app-variables.env
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
