version: "3"

services:
  app:
    image: flamov/flamov-portfolio:latest
    container_name: app
    expose:
      - "3000"
    restart: unless-stopped
    env_file: app-variables.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app-test:3000/status"]
  app-test:
    image: docker.pkg.github.com/flamov/portfolio/portfolio:test
    container_name: app-test
    expose:
      - "3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app-test:3000/status"]
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - app-test
